services:

  # classificatore_nps:
  #   build:
  #     context: ./ClassificatoreNPS
  #   image: clas_nps:latest
  #   container_name: clas_nps
  #   ports:
  #     - "8000:8000"
  #   restart: unless-stopped

  classificatore_nps_mlflow:
    build:
      context: ./ClassificatoreNPS_image
    container_name: clas_nps_mlflow
    hostname: classificatore_nps_mlflow
    environment:
      - MLFLOW_MODELS_WORKERS=1
    restart: unless-stopped

  correction_dispersion:
    build:
      context: ./CorrectionDispersion
    image: correction_dispersion:latest
    container_name: correction_dispersion
    ports:
      - "8001:8001"
    restart: unless-stopped
    volumes:
      - simulation_data:/tmp

  correction_dispersion_mlflow:
    build:
      context: ./CorrectionDispersion_image
    container_name: correction_dispersion_mlflow
    hostname: correction_dispersion_mlflow
    environment:
      - MLFLOW_MODELS_WORKERS=1
    volumes:
      - simulation_data:/simulation_data
    restart: unless-stopped

  gaussian_puff:
    build:
      context: ./gaussianPuff
    image: gaussian_dispersion_model:latest
    container_name: gaussian_dispersion_model
    ports:
      - "8002:8002"
    restart: unless-stopped

  random_sampling:
    build:
      context: ./SamplingService
    image: random_sampling:latest
    container_name: random_sampling
    ports:
      - "8005:8005"
    restart: unless-stopped

  # source_localization:
  #   build:
  #     context: ./EmissionSourceLocalization
  #   image: loc_emission_source:latest
  #   container_name: loc_emission_source
  #   ports:
  #     - "8003:8003"
  #   restart: unless-stopped

  source_localization_mlflow:
    build:
      context: ./EmissionSourceLocalization_image
    container_name: loc_emission_source_mlflow
    hostname: loc_emission_source_mlflow
    environment:
      - MLFLOW_MODELS_WORKERS=1
    restart: unless-stopped

  pention_system:
    build:
      context: .
      dockerfile: PentionSystem/Dockerfile
    image: pention-frontend:latest
    container_name: pention_system
    ports:
      - "8004:8004"
    mem_limit: 16g
    memswap_limit: 16g
    restart: "no"
    volumes:
      - simulation_data:/tmp

volumes:
  simulation_data:
